/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author RandyGUTI
 */
public class FRM_Informacion extends javax.swing.JFrame {

    FRM_Inicio frm_Inicio;
    
    public FRM_Informacion(FRM_Inicio frm_Inicio) {
        initComponents();
        this.setVisible(false);
        this.setLocationRelativeTo(null);
        this.frm_Inicio=frm_Inicio;
        this.jTextArea_Informacion.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Informacion = new javax.swing.JTextArea();
        jl_Fondo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 500));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(null);

        jl_Titulo.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jl_Titulo.setForeground(new java.awt.Color(0, 0, 0));
        jl_Titulo.setText("information");
        getContentPane().add(jl_Titulo);
        jl_Titulo.setBounds(130, 30, 340, 60);

        jTextArea_Informacion.setColumns(20);
        jTextArea_Informacion.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        jTextArea_Informacion.setRows(5);
        jTextArea_Informacion.setText("La historia del juego se basa en la guerra mundial.\nTrata de llevar un avion de guerra lo más lejos posible,\nevitando que otros aviones que se aparezcan en su camino\nlo destruyan.\nLos comandos para poder usar la aplicación son:\n-Las teclas de arriba y abajo se usan para mover nuestro avión\nde guerra.\n-Con el click izquierdo del mouse podemos disparar un misil para \nderribar los aviones enemigos.\n\nEl puntaje del juego se basa en el tiempo que dure antes de que un\navión enemigo lo derribe, en ese momento el juego se acabaría, y se\nagregaría el puntaje a nuestro record de puntos.\n\n");
        jTextArea_Informacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(jTextArea_Informacion);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(140, 150, 330, 200);

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inicio.jpg"))); // NOI18N
        jl_Fondo.setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().add(jl_Fondo);
        jl_Fondo.setBounds(0, 0, 600, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        this.frm_Inicio.setVisible(true);
        this.frm_Inicio.sonido.loop();
    }//GEN-LAST:event_formComponentHidden

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_Informacion;
    private javax.swing.JLabel jl_Fondo;
    private javax.swing.JLabel jl_Titulo;
    // End of variables declaration//GEN-END:variables
}
