/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import static java.applet.Applet.newAudioClip;
import java.applet.AudioClip;
import modelo.MetodosPuntaje;

/**
 *
 * @author RandyGUTI
 */
public class FRM_GameOver extends javax.swing.JFrame {

    /**
     * Creates new form FRM_GameOver
     */
    AudioClip sonido;
    FRM_Inicio inicio;
    public MetodosPuntaje metodos;
    int puntaje;
    
    public FRM_GameOver(FRM_Inicio inicio) {
        initComponents();
        this.inicio=inicio;
        this.setVisible(false);
        this.setLocationRelativeTo(null);
        metodos=new MetodosPuntaje();
    }
    public void efectoGameOver()
    {
      sonido=newAudioClip(getClass().getResource("../audio/fin.wav"));
      sonido.play();
    }
    public void puntaje(int puntaje)
    {
      this.puntaje=puntaje;
    }
    public void limpiarNombre()
    {
      this.jt_Nombre.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_GameOver = new javax.swing.JLabel();
        jl_Nombre = new javax.swing.JLabel();
        jt_Nombre = new javax.swing.JTextField();
        btn_Guardar = new javax.swing.JButton();
        jl_Fondo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(610, 371));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(null);

        jl_GameOver.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 70)); // NOI18N
        jl_GameOver.setForeground(new java.awt.Color(0, 0, 0));
        jl_GameOver.setText("GAME OVER");
        getContentPane().add(jl_GameOver);
        jl_GameOver.setBounds(100, 30, 410, 120);

        jl_Nombre.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 18)); // NOI18N
        jl_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        jl_Nombre.setText("Nombre:");
        getContentPane().add(jl_Nombre);
        jl_Nombre.setBounds(80, 260, 80, 30);

        jt_Nombre.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        getContentPane().add(jt_Nombre);
        jt_Nombre.setBounds(170, 260, 270, 30);

        btn_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btn_Guardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Guardar);
        btn_Guardar.setBounds(460, 250, 60, 50);

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fin.jpg"))); // NOI18N
        getContentPane().add(jl_Fondo);
        jl_Fondo.setBounds(0, 0, 610, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        metodos.escribirEnArchivo();
        this.inicio.setVisible(true);
        this.inicio.sonido.loop();
    }//GEN-LAST:event_formComponentHidden

    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed
        if(metodos.consultarPuntaje(jt_Nombre.getText()))
        {
          if(puntaje>metodos.puntajeGuardar(jt_Nombre.getText()))
          {
             metodos.modificarPuntaje(jt_Nombre.getText(), puntaje);
             limpiarNombre();
          }
        }
        else
        {
          metodos.agregarPuntaje(jt_Nombre.getText(), puntaje);
          limpiarNombre();
        }
    }//GEN-LAST:event_btn_GuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JLabel jl_Fondo;
    private javax.swing.JLabel jl_GameOver;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JTextField jt_Nombre;
    // End of variables declaration//GEN-END:variables
}
