/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import javax.swing.table.DefaultTableModel;
import modelo.MetodosPuntaje;
import modelo.Puntaje;

/**
 *
 * @author RandyGUTI
 */
public class FRM_Puntajes extends javax.swing.JFrame {

    FRM_Inicio frm_Inicio;
    DefaultTableModel modelo;
    MetodosPuntaje metodos;
    
    public FRM_Puntajes(FRM_Inicio frm_Inicio) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(false);
        this.frm_Inicio=frm_Inicio;
        this.metodos=this.frm_Inicio.metodos;
        modelo=new DefaultTableModel();
        this.jTable_Puntajes.setEnabled(false);
        colocarTitulosTabla();
    }
    public void colocarTitulosTabla()
    {
      this.jTable_Puntajes.setModel(modelo);
      modelo.addColumn("Nombre");
      modelo.addColumn("Puntaje");
    }
    public void llenarTablaInicio()
    {
      for(int i=0;i<metodos.getArray().size();i++)
      {
         String[] arreglo=new String[2];
         arreglo[0]=metodos.getArray().get(i).getNombre();
         arreglo[1]=metodos.getArray().get(i).getPuntaje()+"";
         modelo.addRow(arreglo);
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Puntajes = new javax.swing.JTable();
        jl_Fondo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 500));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(null);

        jl_Titulo.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jl_Titulo.setForeground(new java.awt.Color(0, 0, 0));
        jl_Titulo.setText("         bEST sCORES");
        getContentPane().add(jl_Titulo);
        jl_Titulo.setBounds(80, 40, 450, 60);

        jTable_Puntajes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable_Puntajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Puntaje"
            }
        ));
        jScrollPane1.setViewportView(jTable_Puntajes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 190, 340, 90);

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inicio.jpg"))); // NOI18N
        jl_Fondo.setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().add(jl_Fondo);
        jl_Fondo.setBounds(0, 0, 600, 479);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        this.frm_Inicio.setVisible(true);
    }//GEN-LAST:event_formComponentHidden

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Puntajes;
    private javax.swing.JLabel jl_Fondo;
    private javax.swing.JLabel jl_Titulo;
    // End of variables declaration//GEN-END:variables
}
