/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author RandyGUTI
 */
public class FRM_Puntajes extends javax.swing.JFrame {

    FRM_Inicio frm_Inicio;
    
    public FRM_Puntajes(FRM_Inicio frm_Inicio) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(false);
        this.frm_Inicio=frm_Inicio;
    }
    public void llenarTextArea(String msj)
    {
      this.jTextArea_Puntajes.setEditable(false);
      this.jTextArea_Puntajes.setText(msj);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Puntajes = new javax.swing.JTextArea();
        jl_Titulo = new javax.swing.JLabel();
        jl_Fondo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 500));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(null);

        jTextArea_Puntajes.setColumns(20);
        jTextArea_Puntajes.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jTextArea_Puntajes.setRows(5);
        jTextArea_Puntajes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JScrollPane1.setViewportView(jTextArea_Puntajes);

        getContentPane().add(JScrollPane1);
        JScrollPane1.setBounds(120, 140, 370, 270);

        jl_Titulo.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jl_Titulo.setForeground(new java.awt.Color(0, 0, 0));
        jl_Titulo.setText("         bEST sCORES");
        getContentPane().add(jl_Titulo);
        jl_Titulo.setBounds(80, 40, 450, 60);

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inicio.jpg"))); // NOI18N
        jl_Fondo.setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().add(jl_Fondo);
        jl_Fondo.setBounds(0, 0, 600, 479);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        this.frm_Inicio.setVisible(true);
        this.frm_Inicio.sonido.loop();
    }//GEN-LAST:event_formComponentHidden

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane1;
    private javax.swing.JTextArea jTextArea_Puntajes;
    private javax.swing.JLabel jl_Fondo;
    private javax.swing.JLabel jl_Titulo;
    // End of variables declaration//GEN-END:variables
}
