/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import static java.applet.Applet.newAudioClip;
import java.applet.AudioClip;
import modelo.MetodosPuntaje;

/**
 *
 * @author RandyGUTI
 */
public class FRM_Inicio extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Inicio
     */
    public AudioClip sonido;
    FRM_GameOver frm_GameOver;
    FRM_Puntajes frm_Puntajes;
    FRM_Informacion frm_Informacion;
    public MetodosPuntaje metodos;
    public FRM_VentanaJuego frm_VentanaJuego;
    
    public FRM_Inicio() {
        initComponents();
        metodos=new MetodosPuntaje();
        frm_GameOver = new FRM_GameOver(this);
        frm_Puntajes = new FRM_Puntajes(this);
        frm_Informacion=new FRM_Informacion(this);
        this.setLocationRelativeTo(null);
        sonido=newAudioClip(getClass().getResource("../audio/inicio.wav"));
        sonido.loop();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Titulo = new javax.swing.JLabel();
        btn_Jugar = new javax.swing.JButton();
        btn_Record = new javax.swing.JButton();
        btn_Informacion = new javax.swing.JButton();
        jl_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(610, 520));
        getContentPane().setLayout(null);

        jl_Titulo.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jl_Titulo.setForeground(new java.awt.Color(0, 0, 0));
        jl_Titulo.setText("    AIR ATTACK");
        jl_Titulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jl_Titulo);
        jl_Titulo.setBounds(80, 30, 440, 110);

        btn_Jugar.setBackground(new java.awt.Color(51, 51, 51));
        btn_Jugar.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        btn_Jugar.setText("PLAY");
        btn_Jugar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_JugarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Jugar);
        btn_Jugar.setBounds(100, 340, 110, 50);

        btn_Record.setBackground(new java.awt.Color(51, 51, 51));
        btn_Record.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        btn_Record.setText("SCORE");
        btn_Record.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Record.setPreferredSize(new java.awt.Dimension(94, 48));
        btn_Record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RecordActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Record);
        btn_Record.setBounds(380, 340, 110, 50);

        btn_Informacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/informacion.gif"))); // NOI18N
        btn_Informacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Informacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InformacionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Informacion);
        btn_Informacion.setBounds(540, 430, 50, 40);

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inicio.jpg"))); // NOI18N
        jl_Fondo.setText("jLabel1");
        jl_Fondo.setPreferredSize(new java.awt.Dimension(600, 480));
        getContentPane().add(jl_Fondo);
        jl_Fondo.setBounds(0, 0, 600, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_JugarActionPerformed
        // TODO add your handling code here:
        this.sonido.stop();
        this.setVisible(false);
        frm_VentanaJuego = new FRM_VentanaJuego(this.frm_GameOver,this);
    }//GEN-LAST:event_btn_JugarActionPerformed

    private void btn_RecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RecordActionPerformed
       this.sonido.stop();
       this.setVisible(false);
       this.frm_Puntajes.setVisible(true);
       this.frm_Puntajes.llenarTablaInicio();
    }//GEN-LAST:event_btn_RecordActionPerformed

    private void btn_InformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InformacionActionPerformed
        this.sonido.stop();
       this.setVisible(false);
       this.frm_Informacion.setVisible(true);
    }//GEN-LAST:event_btn_InformacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Informacion;
    private javax.swing.JButton btn_Jugar;
    private javax.swing.JButton btn_Record;
    private javax.swing.JLabel jl_Fondo;
    private javax.swing.JLabel jl_Titulo;
    // End of variables declaration//GEN-END:variables
}
